server:
  port: 9005

spring:
   application:
    name: zncloud-gateway
   redis:
     # Redis服务器地址
     host: 47.92.201.212
     # Redis服务器连接端口
     port: 6379
     # Redis服务器连接密码(默认为空)
     password: Szdc123456
     # 连接超时时间(毫秒)
     timeout: 5000
     # Redis数据库索引(默认为0)
     database: 0
   cloud:
     gateway:
       discovery:
         locator:
           enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
#         routes:
#           filters:
#             - name: Hystrix # Hystrix Filter的名称、设置成默认的
#               args: # Hystrix 配置参数
#                 name: fallbackcmd # HystrixCommand 的名字
#                 fallbackUri: forward:/fallback # fallback对用的uri
         #- id: user_routh  #路由的ID，没有固定规则但要求唯一，建议配合服务名
         #uri: lb://mservicecloud-user #匹配后提供服务的路由地址
           #predicates:
           #- Path=/*/*/** # 断言，路径相匹配的进行路由
           lower-case-service-id: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  #       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zncloud-gateway-service
    prefer-ip-address: true     #访问路径可以显示IP地址
